version: "3.3"

services: 
  cmd-api:
    image: comworkio/cmd-api:latest
    user: root
    environment: 
      - API_CMD=sleep 3; ls -l
      - ENABLE_ARGV=enabled
      - REGEXP_ARGV=^\-a$$
    ports: 
      - 8080:8080
