version: "3.3"

services: 
  cmd-api:
    image: comworkio/cmd-api:latest
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - API_CMD=sleep 3; ls -l
    ports: 
      - 8080:8080
